get_hana_meeting_rooms <-
  function()
  {
    
    #create df with additional info about Meeting rooms
    
    hana_location<-c("Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park District",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place",
                     "Park Place"
                     )
    
    resourceid<-c(
      1083194117,
      1083194121,
      1083206131,
      1083206132,
      1083206133,
      1083206134,
      1083206135,
      1083610530,
      1083610531,
      1083610532,
      1083610533,
      1083720645,
      1083720646,
      1083720647,
      1083720648,
      1083720649,
      1083720650,
      1119864747,
      1147624492,
      1198899721,
      1198899723,
      1198899724,
      1198899725,
      1198900724,
      1198902715,
      1198902716,
      1198902718,
      1199135952,
      1199135954,
      1199135955,
      1199135957,
      1199135959,
      1199135960,
      1199135961,
      1199135962,
      1212667468,
      1199135956,
      1198902717,
      1198899722
      )
    
    room_name<-c(
      "3-21 Aday Project Room",
      "3-08 Jones Conference Room",
      "3-04 Trevino Pitch Room",
      "3-23 Kilby Conference Room",
      "3-15 Rousseau Lounge",
      "3-12 Carter Conference Room",
      "3-16 Quinn Conference Room",
      "3-05 Maceo Smith Conference Room",
      "3-22 Perot Conference Room",
      "3-20 Nesmith Room",
      "3-02 Judd Room",
      "3-07 Gates Lounge",
      "3-11 Reynolds Lounge",
      "3-01 Walker Lounge",
      "3-09 Wetzel Conference Room",
      "3-06 Rather Conference Room",
      "Wellness Room 4th Floor",
      "3-03 Vincent Lounge",
      "Training Room",
      "M20 Cohen Lounge",
      "M13 Keaton Conference Room",
      "M17 Pico Conference Room",
      "M7 Autry Conference Room",
      "M18 Conley Conference Room",
      "M15 Johnson Lounge",
      "M9 Brando Conference Room",
      "M6 Portola Pitch Room",
      "M16 Broadus Lounge",
      "M10 Morhaime Huddle Room",
      "M4 Ocean Lounge",
      "M2 Martin Huddle Room",
      "M1 Wayne Conference Room",
      "M19 Ferrell Lounge",
      "M14 Fender Lounge",
      "M12 Pfeiffer Lounge",
      "M8 Snyder Training Room",
      "M3 Davenport Huddle Room",
      "M11 Hansen Meeting Room",
      "M5 Klein Lounge"
      )
    
    room_id<-c(
      "3-21",
      "3-08",
      "3-04",
      "3-23",
      "3-15",
      "3-12",
      "3-16",
      "3-05",
      "3-22",
      "3-20",
      "3-02",
      "3-07",
      "3-11",
      "3-01",
      "3-09",
      "3-06",
      "Wellness",
      "3-03",
      "3A",
      "M20",
      "M13",
      "M17",
      "M7",
      "M18",
      "M15",
      "M9",
      "M6",
      "M16",
      "M10",
      "M4",
      "M2",
      "M1",
      "M19",
      "M14",
      "M12",
      "M8",
      "M3",
      "M11",
      "M5"
      )
    
    seating_type<-c(
      "War Room",
      "Standing",
      "Hybrid",
      "Seated",
      "Lounge",
      "Seated",
      "Seated",
      "Seated",
      "Seated",
      "Standing",
      "Seated",
      "Lounge",
      "Lounge",
      "Lounge",
      "Standing",
      "Seated",
      "N/A",
      "Lounge",
      "Seated",
      "Lounge",
      "Table",
      "Seated",
      "Seated",
      "Seated",
      "Lounge",
      "Table",
      "Hybrid",
      "Lounge",
      "Standing",
      "Lounge",
      "Standing",
      "Seated",
      "Lounge",
      "Lounge",
      "Lounge",
      "Training",
      "Lounge",
      "Mobile",
      "Lounge"
      )
    
    room_type<-c(
      "Dancing Room",
      "7p Conference Room",
      "Pitch Room",
      "12p Conference Room",
      "Lounge",
      "9p Conference Room",
      "9p Conference Room",
      "6p Conference Room",
      "6p Conference Room",
      "5p Meeting Room",
      "4p Meeting Room",
      "Lounge",
      "Lounge",
      "Lounge",
      "7p Conference Room",
      "4p Conference Room",
      "Wellness Room",
      "Lounge",
      "Training Room",
      "Lounge",
      "Table",
      "Seated VTC Table",
      "Seated Table",
      "Seated VTC Table",
      "Lounge",
      "Table",
      "Pitch Room",
      "Lounge",
      "Standing Height VTC Table",
      "Lounge",
      "Standing Height VTC Table",
      "Seated Table",
      "Lounge",
      "Lounge",
      "Lounge",
      "Training Room",
      "Lounge",
      "Mobile Laptop Chair",
      "Lounge"
      )
    
    current_room_size<-c(
      "Large Conference Room ",
      "Medium Conference Room ",
      "Large Lounge ",
      "Large Conference Room ",
      "Medium Lounge ",
      "Medium Conference Room ",
      "Medium Conference Room ",
      "Medium Conference Room ",
      "Medium Lounge ",
      "Huddle Room ",
      "Huddle Room ",
      "Huddle Room ",
      "Medium Lounge ",
      "Huddle Room ",
      "Medium Conference Room ",
      "Huddle Room ",
      "Wellness Room ",
      "Medium Conference Room ",
      "Converted Rooms ",
      "Small Room ",
      "Medium Room ",
      "Medium Room ",
      "Large Room ",
      "Medium Room ",
      "Medium Room ",
      "Medium Room ",
      "Large Room ",
      "Small Room ",
      "Small Room ",
      "Small Room ",
      "Small Room ",
      "Small Room ",
      "Small Room ",
      "Medium Room ",
      "Medium Room ",
      "Training Room ",
      "Small Room",
      "Medium Room",
      "Small Room"
    )
    
    zoom_room_id<-c(
      "Aday 3-21",
      "Jones 3-08",
      "Trevino 3-04",
      "Kilby 3-23",
      "Rousseau 3-15",
      "Carter 3-12",
      "Quinn 3-16",
      "Maceo Smith 3-05",
      "Perot 03-22",
      "Nesmith 3-20",
      "Judd 3-02",
      "Gates 3-07",
      "Reynolds 3-11",
      "Walker 3-01",
      "Wetzel 3-09",
      "Rather 3-06",
      "NA",
      "Vincent 3-03",
      "Hana Meeting Room 1",
      "Cohen Lounge",
      "Keaton Conf Rm",
      "Pico Conf Rm",
      "Autry Conf Rm",
      "Conley Conf Rm",
      "Johnson Lounge",
      "Brando Conf Rm",
      "Portola Pitch Rm",
      "Broadus Lounge",
      "Morhaime Huddle Rm",
      "Ocean Lounge",
      "Martin Huddle Rm",
      "Wayne Conf Rm",
      "Ferrell Lounge",
      "Fender Lounge",
      "Pfeiffer Lounge",
      "Snyder Training Rm",
      "Davenport Huddle Rm",
      "Hansen Meeting Rm",
      "Klein Lounge"
    )
    
    max_density<-c(
      16,
      7,
      14,
      12,
      8,
      9,
      9,
      6,
      6,
      5,
      4,
      5,
      6,
      4,
      7,
      4,
      1,
      8,
      24,
      2,
      6,
      9,
      12,
      9,
      8,
      6,
      14,
      2,
      4,
      4,
      4,
      4,
      4,
      8,
      6,
      24,
      4,
      6,
      2
      )
    
    credits<-c(
      4,
      3,
      4,
      4,
      3,
      3,
      3,
      3,
      3,
      2,
      2,
      2,
      3,
      2,
      3,
      2,
      0,
      3,
      6,
      2,
      3,
      3,
      4,
      3,
      3,
      3,
      4,
      2,
      2,
      2,
      2,
      2,
      2,
      3,
      3,
      6,
      2,
      3,
      2
      )
    
    sq_ftg<-c(
      494,
      243,
      401,
      376,
      277,
      420,
      257,
      164,
      190,
      116,
      156,
      235,
      275,
      153,
      267,
      136,
      60,
      206,
      1255,
      81,
      208,
      282,
      407,
      282,
      250,
      215,
      517,
      64,
      119,
      136,
      129,
      132,
      123,
      252,
      219,
      873,
      136,
      164,
      75
      )
    

    
    hana_meeting_rooms<-data.frame(hana_location,resourceid,room_name,room_id,seating_type,room_type,zoom_room_id, current_room_size,max_density,sq_ftg,stringsAsFactors = FALSE)
    
    hana_meeting_rooms
    
  }